### ISSUE TITLE
All Tracks require an artist and a track

### ISSUE THREAD

**Issue by BoBeR182** [Laharah/redlist#3]
```
Fetching playlist 37i9dQZF1DXd6tJtr4qeot from spotify.
Matching track list to beets library...
Finished. There are 28 tracks that could not be matched.
Writing m3u file to /home/bober/redlist/Punk Essentials.m3u.

The following tracks could not be matched to your beets library:
Foo Fighters - The Colour And The Shape - Monkey Wrench
Pennywise - Land Of The Free? - Fuck Authority
Rancid - Indestructible - Fall Back Down
Bad Religion - Recipe For Hate - American Jesus
Alkaline Trio - Crimson - Mercy Me
Millencolin - Pennybridge Pioneers - No Cigar
Bad Religion - Stranger Than Fiction - 21st Century [Digital Boy]
Sugarcult - Lights Out - Los Angeles
Jimmy Eat World - Bleed American (Deluxe Edition) - The Middle
The Offspring - Rise And Fall, Rage And Grace - You're Gonna Go Far, Kid
Anti-Flag - For Blood And Empire - This Is the End (For You My Friend)
AFI - DECEMBERUNDERGROUND - Miss Murder
NOFX - The War On Errorism - Franco Un-American
The Ataris - So Long, Astoria - The Boys of Summer
Less Than Jake - Hello Rockview - All My Best Friends Are Metalheads
NOFX - White Trash ...... - Bob
Jimmy Eat World - Futures (Deluxe Version) - Pain
Pennywise - Pennywise - Bro Hymn
Rancid - ...And Out Come The Wolves - Ruby Soho
Lagwagon - Let's Talk About Feelings (Reissue) - May 16
Anti-Flag - For Blood And Empire - The Press Corpse
The Distillers - Sing Sing Death House - City Of Angels
Millencolin - Home From Home - Kemp
NOFX - Pump Up The Valuum - Dinosaurs Will Die
Anti-Flag - The Terror State - Turncoat
Alkaline Trio - From Here to Infirmary - Private Eye
Social Distortion - White Light White Heat White Trash - I Was Wrong
Against Me! - New Wave (U.S. Version) - Thrash Unreal

Connecting to [REDACTED]...
SUCCESS!
Begining search for 28 tracks, This may take a while.
[REDACTED]: hit on first try for Pennywise - Land Of The Free? - Fuck Authority
[REDACTED]: hit on first try for Rancid - Indestructible - Fall Back Down
[REDACTED]: hit on first try for Bad Religion - Recipe For Hate - American Jesus
[REDACTED]: hit on first try for Alkaline Trio - Crimson - Mercy Me
[REDACTED]: hit on first try for Millencolin - Pennybridge Pioneers - No Cigar
[REDACTED]: widening search for Bad Religion - Stranger Than Fiction - 21st Century [Digital Boy]...
[REDACTED]: hit on first try for Sugarcult - Lights Out - Los Angeles
[REDACTED]: hit on first try for Foo Fighters - The Colour And The Shape - Monkey Wrench
[REDACTED]: hit on first try for The Offspring - Rise And Fall, Rage And Grace - You're Gonna Go Far, Kid
[REDACTED]: widening search for Anti-Flag - For Blood And Empire - This Is the End (For You My Friend)...
[REDACTED]: hit on first try for AFI - DECEMBERUNDERGROUND - Miss Murder
[REDACTED]: Considering For Blood and Empire: id=1793959 for "This Is the End (For You My Friend)"
[REDACTED]: widening search for NOFX - The War On Errorism - Franco Un-American...
[REDACTED]: widening search for Jimmy Eat World - Bleed American (Deluxe Edition) - The Middle...
[REDACTED]: hit on first try for The Ataris - So Long, Astoria - The Boys of Summer
[REDACTED]: Considering Stranger Than Fiction: id=1698497 for "21st Century [Digital Boy]"
[REDACTED]: widening search for NOFX - White Trash ...... - Bob...
[REDACTED]: Found torrent for "Anti-Flag - For Blood And Empire - This Is the End (For You My Friend)" with 71.2% confidence.
[REDACTED]: hit on first try for Less Than Jake - Hello Rockview - All My Best Friends Are Metalheads
[REDACTED]: Unable to find torrent for Jimmy Eat World - Bleed American (Deluxe Edition) - The Middle
[REDACTED]: Could not find Bleed American (Deluxe Edition), Checking other albums by Jimmy Eat World.
[REDACTED]: hit on first try for Pennywise - Pennywise - Bro Hymn
[REDACTED]: widening search for Jimmy Eat World - Futures (Deluxe Version) - Pain...
[REDACTED]: Found torrent for "Bad Religion - Stranger Than Fiction - 21st Century [Digital Boy]" with 71.4% confidence.
[REDACTED]: Unable to find torrent for NOFX - White Trash ...... - Bob
[REDACTED]: Could not find White Trash ......, Checking other albums by NOFX.
[REDACTED]: widening search for Lagwagon - Let's Talk About Feelings (Reissue) - May 16...
[REDACTED]: hit on first try for Anti-Flag - For Blood And Empire - The Press Corpse
[REDACTED]: Considering White Trash, Two Heebs and a Bean: id=937129 for "Bob"
[REDACTED]: Unable to find torrent for Lagwagon - Let's Talk About Feelings (Reissue) - May 16
[REDACTED]: Could not find Let's Talk About Feelings (Reissue), Checking other albums by Lagwagon.
[REDACTED]: hit on first try for Rancid - ...And Out Come The Wolves - Ruby Soho
[REDACTED]: hit on first try for The Distillers - Sing Sing Death House - City Of Angels
[REDACTED]: Considering Bleed American: id=957163 for "The Middle"
[REDACTED]: Considering The War on Errorism: id=429971 for "Franco Un-American"
[REDACTED]: hit on first try for Millencolin - Home From Home - Kemp
[REDACTED]: hit on first try for NOFX - Pump Up The Valuum - Dinosaurs Will Die
[REDACTED]: Considering Let's Talk About Feelings: id=833343 for "May 16"
[REDACTED]: Unable to find torrent for Jimmy Eat World - Futures (Deluxe Version) - Pain
[REDACTED]: Could not find Futures (Deluxe Version), Checking other albums by Jimmy Eat World.
[REDACTED]: hit on first try for Anti-Flag - The Terror State - Turncoat
[REDACTED]: Found torrent for "Lagwagon - Let's Talk About Feelings (Reissue) - May 16" with 100.0% confidence.
[REDACTED]: Considering Futures: id=2531384 for "Pain"
[REDACTED]: Found torrent for "NOFX - The War On Errorism - Franco Un-American" with 70.3% confidence.
[REDACTED]: Found torrent for "Jimmy Eat World - Futures (Deluxe Version) - Pain" with 100.0% confidence.
[REDACTED]: hit on first try for Alkaline Trio - From Here to Infirmary - Private Eye
[REDACTED]: hit on first try for Social Distortion - White Light White Heat White Trash - I Was Wrong
[REDACTED]: Found torrent for "NOFX - White Trash ...... - Bob" with 100.0% confidence.
[REDACTED]: Considering Bleed American Demos: id=241293 for "The Middle"
ERROR:redlist.__main__:Error Processing https://open.spotify.com/playlist/37i9dQZF1DXd6tJtr4qeot.
Traceback (most recent call last):
  File "/home/bober/redlist/lib/python3.8/site-packages/redlist/__main__.py", line 233, in entry_point
    results.append(loop.run_until_complete(main(splist, options.yes)))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/bober/redlist/lib/python3.8/site-packages/redlist/__main__.py", line 84, in main
    await asyncio.gather(*tasks.values())
  File "/home/bober/redlist/lib/python3.8/site-packages/redlist/redsearch.py", line 88, in find_album
    hit = await search_torrent_groups(track_info,
  File "/home/bober/redlist/lib/python3.8/site-packages/redlist/redsearch.py", line 149, in search_torrent_groups
    canidate_info = matching.TrackInfo(title=track_canidate,
  File "/home/bober/redlist/lib/python3.8/site-packages/redlist/matching.py", line 28, in __init__
    raise ValueError("All Tracks require an artist and a track")
ValueError: All Tracks require an artist and a track
```

**Comment by Laharah** [comment]
I couldn't replicate that error you got for that particular torrent, but I did do some more work on the search system, so that a single failed torrent won't crash the whole search. I'm gonna mark this as closed, if it's still happening re-open and I'll see if we can do some more in-depth debugging.

**Comment by BoBeR182** [comment]
I think it was related to the actual playlist not to do with the torrent.
Also not sure if it's a diff bug, but it seems it skips the first song, but only in debug output, not in searching for the torrent. Updating now and I'll reopen if it crashes again. Thank you so much for maintaining the script.

This was the bugged torrent 
```
ERROR:redlist.redsearch:could not make TrackInfo for Jimmy Eat World - Bleed American (Deluxe Edition) - The Middle.
```
From this playlist https://open.spotify.com/playlist/37i9dQZF1DXd6tJtr4qeot

**Comment by Laharah** [comment]
Yeah, that's an error when it's trying to verify that the track you're looking for is in a particular torrent. It has to create a dummy track for the file name. I think there might be an issue where the filters are too aggressive and are accidentally wiping the entire file name.

Can you send me the output of `redlist --show-config`? When I was trying to replicate that's the track I tested on and didn't have any trouble with it. There might be a problem with a specific format you're trying to get on Red. 

Also, I think that might be a dynamic playlist on spotify, because that track isn't on the playlist for me. There seems to be a bunch of differences from the one you posted above too. This is what it looks like for me:

01. The Viking - Lars Frederiksen and the Bastards - Viking
02. Weird Beard - Mad Caddies - Rock The Plank
03. The Three of Us - Streetlight Manifesto - The Hands That Thieve
04. Come With Me - Deviates - Time Is The Distance
05. Diamonds And Guns - Transplants - Transplants
06. Question The Answer - Strike Anywhere - To Live In Discontent
07. Banquet - Bloc Party - Silent Alarm (U.S. Version)
08. State of Mind - Mad Caddies - Consentual Selections
09. Point / Counterpoint - Streetlight Manifesto - Everything Goes Numb
10. Take Warning - Operation Ivy - Operation Ivy (2007 Remaster)
11. Insubordination - Voodoo Glow Skulls - Who Is, This Is?
12. Shining On - Big D and the Kids Table - Strictly Rude
13. Heart Attack American - The Bronx - The Bronx (I)
14. Mexican Radio - Authority Zero - Andiamo (Explicit Content U.S. Version)
15. Such Great Heights - Streetlight Manifesto - 99 Songs of Revolution Vol. 1
16. New Noise - Refused - The Shape Of Punk To Come
17. One Armed Scissor - At The Drive In - Relationship of Command
18. El Coo Cooi - Voodoo Glow Skulls - Firme
19. Road Rash - Mad Caddies - Duck And Cover
20. Mr. Smiley - Mustard Plug - Big Daddy Multitude
21. Everything Went Numb - Streetlight Manifesto - Everything Goes Numb
22. Pints of Guinness Make You Strong - Against Me! - Reinventing Axl Rose
23. Rebel Yell - Assorted Jelly Beans - What's Really Going On!?!
24. Sound System - Operation Ivy - Operation Ivy (2007 Remaster)
25. Knifeman - The Bronx - The Bronx (III)
26. This Is How It Goes - Billy Talent - Billy Talent
27. We Will Fall Together - Streetlight Manifesto - Somewhere in the Between
28. Not Fucking Around - Big D and the Kids Table - Fluent In Stroll
29. Shoot the Moon - Voodoo Glow Skulls - Firme
30. State Of The Union - Rise Against - Siren Song Of The Counter-Culture
31. Fred's Got Slacks - The Flatliners - Destroy To Create
32. Fell in Love with a Girl - The White Stripes - White Blood Cells
33. On a Rope - Rocket From The Crypt - Scream, Dracula, Scream
34. Refusal - Strike Anywhere - Change Is A Sound
35. Hate To Say I Told You So - The Hives - Your New Favourite Band
36. Patent Pending - Heavens - Patent Pending
37. Superman - Goldfinger - The Best Of Goldfinger
38. New Girl - The Suicide Machines - Destruction By Definition
39. Kids Of The K-Hole - NOFX - So Long & Thanks For All The Shoes
40. Insects Destroy - Pulley - Matters
41. Main Offender - The Hives - Veni Vidi Vicious
42. Counting - Heavens - Patent Pending
43. Back To The Motor League - Propagandhi - Today's Empires, Tomorrow's Ashes
44. Celebration Song - Unwritten Law - Here's To The Mourning
45. Kemp - Millencolin - Home From Home
46. Society - Pennywise - Full Circle (2005 Remaster)
47. 'Merican - Descendents - Cool To Be You
48. Tick Tick Boom - The Hives - The Black And White Album
49. Gangsters and Thugs - Transplants - Haunted Cities
50. Euro-Barge - The Vandals - Hitler Bad, Vandals Good

**Comment by BoBeR182** [comment]
Interesting, I never heard of dynamic playlists.
Here is my config file attached.
```
beets_library: /home/bober/.config/beets/library.db
torrent_directory: .
m3u_directory: .
enable_deluge: yes
restrict_album: no
overwrite_m3u: no

redacted:
    username: REDACTED
    password: REDACTED
    save_cookies: yes
    use_fl_tokens: yes
    format_preferences:
    - FLAC .* (Web)
    - FLAC .* (lossless)
    - FLAC .*
    - MP3 V0
    - MP3 .*
    - .*

deluge:
    host: localhost
    port: 58846
    username: REDACTED
    password: REDACTED
    add_paused: yes
pinentry: yes

```

**Comment by Laharah** [comment]
I still can't get replicate the error on my side. If you don't mind, would you be willing to update to the new version and send me the `ERROR:redlist.redsearch:could not make TrackInfo` error you get when you re-run? 

The new version should be more explicit about what filename exactly is causing it to fail. It'll help me better tune the filename filters.

**Comment by BoBeR182** [comment]
Sorry, It was fixed in your last patch. I can't replicate it either.
I thought you might have wanted to know what the actual file was, but it's too late now, without downgrading and manually removing that album from my beets library.
